global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'wasteless-backend'
    static_configs:
      - targets: ['host.docker.internal:4000', 'backend:4000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
